---
    language: cpp
    matrix:
      include:
        # Ubuntu 20.04 + gcc on amd64
        - arch: amd64
          os: linux
          dist: focal
          compiler: gcc
        # Ubuntu 20.04 + clang on amd64
        - arch: amd64
          os: linux
          dist: focal
          compiler: clang
        # Ubuntu 18.04 + gcc on amd64
        - arch: amd64
          os: linux
          dist: bionic
          compiler: gcc
        # Ubuntu 18.04 + clang on amd64
        - arch: amd64
          os: linux
          dist: bionic
          compiler: clang
        # Ubuntu 16.04 + gcc on amd64
        - arch: amd64
          os: linux
          dist: xenial
          compiler: gcc
        # Ubuntu 16.04 + clang on amd64
        - arch: amd64
          os: linux
          dist: xenial
          compiler: clang
        # Ubuntu 20.04 + gcc on ppc64le
        - arch: ppc64le
          os: linux
          dist: focal
          compiler: gcc
        # Ubuntu 20.04 + clang on ppc64le
        - arch: ppc64le
          os: linux
          dist: focal
          compiler: clang
        # Ubuntu 18.04 + gcc on ppc64le
        - arch: ppc64le
          os: linux
          dist: bionic
          compiler: gcc
        # Ubuntu 18.04 + clang on ppc64le
        - arch: ppc64le
          os: linux
          dist: bionic
          compiler: clang
        # Ubuntu 16.04 + gcc on ppc64le
        - arch: ppc64le
          os: linux
          dist: xenial
          compiler: gcc
        # Ubuntu 16.04 + clang on ppc64le
        - arch: ppc64le
          os: linux
          dist: xenial
          compiler: clang
    before_install:
      - |
        # PGASUS dependencies
        sudo apt-get -y install libnuma-dev zlib1g-dev libhwloc-common libhwloc-dev
        
        # Download and build Boost 1.60
        wget -O /tmp/boost_1_60_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz/download
        cd /tmp/ 
        tar -xzf boost_1_60_0.tar.gz
        cd /tmp/boost_1_60_0
        ./bootstrap.sh --with-libraries=context,chrono,thread,system
        ./b2
        sudo ./b2 install
        cd /tmp
        rm -Rf /tmp/boost_1_60_0
    script:
      - |
        # Build PGASUS
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        sudo make -j"$(nproc)"
    